TOKENS = [
   ('tk_int',      r'^\bint\b'),
   ('tk_float',    r'^\bfloat\b'),
   ('tk_char',     r'^\bchar\b'),
   ('tk_double',   r'^\bdouble\b'),
   ('tk_struct',   r'^\bstruct\b'),

   ('tk_logical_and', r"^&{2}"),
   ('tk_logical_or', r"^\|{2}"),
   ('tk_logical_equal', r"^={2}"),
   ('tk_bitwise_left_shift', r"^<{2}"),
   ('tk_bitwise_right_shift', r"^>{2}"),
   ('tk_logical_greater_equal', r'^\b>=\b'),
   ('tk_logical_lesser_equal', r'^\b<=\b'),
   ('tk_logical_not_equal', r'^!='),

   ('tk_logical_greater', r'^>'),
   ('tk_logical_lesser', r'^<'),
   ('tk_logial_not', r"^\!"),
   ('tk_bitwise_and', r"^&"),
   ('tk_bitwise_or', r"^\|"),
   ('tk_bitwise_xor', r"^\^"),
   ('tk_bitwise_not', r"^\~"),
   ('tk_assignment', r"^="),
   ('tk_comma', r'^\,'),
   ('tk_open_parenthesis', r'^\('),
   ('tk_close_parenthesis', r'^\)'),
   ('tk_open_bracket', r"^\["),
   ('tk_close_bracket', r'^\]'),
   ('tk_open_brace', r'^{'),
   ('tk_close_brace', r'^}'),
   ('tk_semicolon', r"^;"),
   ('tk_point', r"^\."),
   ('tk_colon', r"^\:"),
   ('tk_op', r'^[+\-*/%]'),
   ('tk_const', r"^\d+(\.\d+)?"),
   ('tk_id', r'^[a-zA-Z_][a-zA-Z0-9_]*')
]